testing husky again

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,16 +1,27 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-# Color variables
+# Define ANSI color codes
 RED='\033[0;31m'
 GREEN='\033[0;32m'
 YELLOW='\033[1;33m'
 NC='\033[0m' # No Color
 
+# Function to check if command succeeded
+check_command() {
+  if [ $? -eq 0 ]; then
+    echo "${GREEN}$1 succeeded${NC}"
+  else
+    echo "${RED}$1 failed${NC}"
+  fi
+}
+
 # Running tests
-echo "${YELLOW}Running tests...${NC}"
-yarn test && echo "${GREEN}Tests completed.${NC}" || echo "${RED}Tests failed.${NC}"
+echo -e "${YELLOW}Running tests...${NC}"
+yarn test
+check_command "Tests"
 
 # Running linter
-echo "${YELLOW}Running linter...${NC}"
-yarn lint && echo "${GREEN}Linting completed.${NC}" || echo "${RED}Linting failed.${NC}"
+echo -e "${YELLOW}Running linter...${NC}"
+yarn lint
+check_command "Linting"
